//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class InGameCore : MonoBehaviour
{
	public LevelManager levelManager;
	public Session currentSession;

	public static string levelToLoad = "Levels/1";

	private static InGameCore _instance = null;
    public static InGameCore Instance { get {
				return InGameCore._instance == null ? 
					new InGameCore() : InGameCore._instance;
		} }
		

	void Awake(){

	}

	void Start(){
		Run ();
	}
	
	public void Run(){
		GameObject go = new GameObject("Session");
		this.currentSession = go.AddComponent<Session>();
		this.levelManager.LoadResource( this.currentSession , InGameCore.levelToLoad );
	}

	public void Reset(){

		if( currentSession != null ){
			Destroy( currentSession );
		}

		Run ();

	}

	void Update()
	{

		if( Input.GetKeyDown(KeyCode.Space) )
		{
			Debug.Log("RESET");
			//Reset();
		}
	}

}




